# Generated by Django 4.0.2 on 2022-02-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounttree', '0005_alter_account_id'),
        ('interview', '0002_interview_interviewee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounttree.account'),
        ),
    ]
