# Generated by Django 2.0.5 on 2018-05-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounttree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_level',
            field=models.CharField(choices=[('GAL', 'Global Admin'), ('COL', 'Account Owner'), ('CAL', 'Administrator'), ('CUL', 'User'), ('CCL', 'Contact')], default='CCL', max_length=3),
            preserve_default=False,
        ),
    ]
