# Generated by Django 2.0.5 on 2018-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounttree', '0002_account_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_level',
            field=models.CharField(choices=[('GAL', 'Global Admin'), ('COL', 'Account Owner'), ('CAL', 'Administrator'), ('CUL', 'User'), ('CCL', 'Contact')], default='CCL', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('ORG', 'Organization'), ('PER', 'Person')], default='PER', max_length=3),
        ),
    ]
