# Generated by Django 2.0.5 on 2018-05-26 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounttree', '0003_auto_20180525_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='account_type',
        ),
    ]
